import io

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from backend.session_store import get_session

router = APIRouter()


@router.get("/download/{session_id}")
def download(session_id: str):
    sess = get_session(session_id)
    if not sess:
        raise HTTPException(404, "Session not found.")

    # Serve pre-generated bytes if available (instant)
    excel_bytes = sess.get("excel_bytes")
    if not excel_bytes:
        raise HTTPException(404, "Download not ready yet. Please run the pipeline first.")

    fname = sess.get("file_name", "output").rsplit(".", 1)[0]
    return StreamingResponse(
        io.BytesIO(excel_bytes),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f'attachment; filename="{fname}_qc_output.xlsx"'},
    )
